### ISSUE TITLE
Questions about the dataset

### ISSUE THREAD

**Issue by Luyunfei0728** [zjunlp/WKM#4]
Dear author, when I was reproducing your work, I followed the steps given in the readme and found that there was no "chosen" key value in the data set when I executed the world_knowledge_build.py script. Could you please provide the data set you used? Thank you very much.

**Comment by Rolnand** [comment]
We have uploaded the [dataset](https://huggingface.co/datasets/zjunlp/WKM_pair_data). You are welcome to use it!

If you need any more help, feel free to ask!

**Comment by Luyunfei0728** [comment]
I'm really sorry to trouble you again. When I run train_data_process.py, there is a keyword called "guideline", which is also missing. Could you please kindly answer it?

**Comment by Rolnand** [comment]
Sorry for the inconvenience caused to you. You can replace the keyword "guideline" to "task_knowledge", and "state" to "state_knowledge"

**Comment by Luyunfei0728** [comment]
Okay, thank you very much for your patience.
