### ISSUE TITLE
Dataset questions

### ISSUE THREAD

**Issue by Jerry-hyl** [zjunlp/WKM#5]
Dear author, when I was reproducing your work, I have a small question. Which base model is the train data `train_data_for_agent.json` and `train_data_for_wm.json` inferred with? In your paper, I found that the task knowledge and the state knowledge is generated by the agent model itself, which is only 8b or 7b in parameter. I'm really confused with this question. Hope you can give me an answer. Thank you very much!

**Comment by GoooDte** [comment]
Hello, thanks for your interest in our work.
The training data we provide are sourced from Mistral-7B.

**Comment by Jerry-hyl** [comment]
Thank you for your response. However, I still have some questions regarding the code for structuring the data for agent training. On line 85 of [train_data_process.py](https://github.com/zjunlp/WKM/blob/main/src/train_data_process.py),`human_conv += convs[i]["state_knowledge"]` shows that state knowledge is included during the training of agent model, which is different from what's said in the paper and the training data given. Is there a mistake?

**Comment by Rolnand** [comment]
You're right, state_knowledge is not in the agent's training data. There should have been a comment symbol before human_conv += convs[i]["state_knowledge"], but we forgot to add it back while debugging the code. You can refer to the latest train_data_process.py.

**Comment by Jerry-hyl** [comment]
Okay, thank you very much for your patience.

**Comment by Jerry-hyl** [comment]
Sorry, but could you please provide the eval set you used? When I follow the eval steps provided in the `README.md`, I found that `FileNotFoundError: [Errno 2] No such file or directory: 'eval_agent/data/sciworld/test_indices.json'` Thank you very much.

**Comment by Jerry-hyl** [comment]
By the way, what does the `LLaMA-Factory/lora` directory in `fastchat_agent.py` refer to?

**Comment by Rolnand** [comment]
> Sorry, but could you please provide the eval set you used? When I follow the eval steps provided in the `README.md`, I found that `FileNotFoundError: [Errno 2] No such file or directory: 'eval_agent/data/sciworld/test_indices.json'` Thank you very much.

You can download it from [here](https://github.com/Yifan-Song793/ETO/tree/main/eval_agent/data)

**Comment by Rolnand** [comment]
> By the way, what does the `LLaMA-Factory/lora` directory in `fastchat_agent.py` refer to?

refer to the lora weight trained by LLaMA-Factory in your local path

**Comment by Jerry-hyl** [comment]
Thank you for your answer! I have successfully build the whole project with your help! But during my evaluation and inference process, each test case ends with the error `exceeding maximum input length`. I have confirmed that this error happens when calculating the probability of the first token of the action, so the output always ends the case like: `"Thought: xxx:\nAction:"`, what can I do to solve this problem?

**Comment by Rolnand** [comment]
Could you show the trajectory and detailed error information?

**Comment by Jerry-hyl** [comment]
One trajectory example is:
```json
{
    "meta": {
        "steps": 1,
        "reward": 0.0,
        "finished": true,
        "success": false,
        "terminate_reason": "exceeding maximum input length",
        "error": null
    },
    "conversations": [
        {
            "from": "human",
            "value": "You are a helpful assistant to do some scientific experiment in an environment.\nIn the environment, there are several rooms: kitchen, foundry, workshop, bathroom, outside, living room, bedroom, greenhouse, art studio, hallway\nAt first you will be given a Task Knowledge to help finish the task.\nTask Knowledege will guide you how to finish the task.\nYou should explore the environment and find the items you need to complete the experiment.\nYou can teleport to any room in one step.\nAll containers in the environment have already been opened, you can directly get items from the containers.\n\nThe available actions are:\nopen OBJ: open a container\nclose OBJ: close a container\nactivate OBJ: activate a device\ndeactivate OBJ: deactivate a device\nconnect OBJ to OBJ: connect electrical components\ndisconnect OBJ: disconnect electrical components\nuse OBJ [on OBJ]: use a device/item\nlook around: describe the current room\nexamine OBJ: describe an object in detail\nlook at OBJ: describe a container's contents\nread OBJ: read a note or book\nmove OBJ to OBJ: move an object to a container\npick up OBJ: move an object to the inventory\npour OBJ into OBJ: pour a liquid into a container\nmix OBJ: chemically mix a container\nteleport to LOC: teleport to a specific room\nfocus on OBJ: signal intent on a task object\nwait: task no action for 10 steps\nwait1: task no action for a step"
        },
        {
            "from": "gpt",
            "value": "OK"
        },
        {
            "from": "human",
            "value": "Task Description:\nYour task is to boil tin. For compounds without a boiling point, combusting the substance is also acceptable. First, focus on the substance. Then, take actions that will cause it to change its state of matter.\nTask Knowledge: When tasked with boiling or combusting a substance in the environment, follow these steps:\n\n1. Identify the substance: Look around the current room or examine the inventory to find the substance.\n2. Focus on the substance: Signal intent on the substance to prepare for further actions.\n3. Check the substance's state: Look at or examine the substance to determine if it's a liquid, solid, or gas.\n4. If the substance is a solid or liquid, heat it: Teleport to the kitchen or foundry and look around for a suitable container with"
        },
        {
            "from": "gpt",
            "value": "Thought: I need to identify the substance I'm supposed to boil. The task description mentions \"tin,\" but it's not clear if \"tin\" is a substance or an object. I should look around the current room to find out.\nAction: look around"
        },
        {
            "from": "human",
            "value": "Observation: This room is called the bathroom. In it, you see: \n\tthe agent\n\ta substance called air\n\ta bathtub, which is turned off. In the bathtub is: nothing.\n\ta drawing\n\ta glass cup (containing nothing)\n\ta sink, which is turned off. In the sink is: nothing.\n\ta toilet. In the toilet is: A drain, which is open, a substance called water.\nYou also see:\n\tA door to the kitchen (that is open)"
        },
        {
            "from": "gpt",
            "value": "Thought: I'm in the bathroom, but I don't see any tin here. The task description mentions a kitchen, which is a more likely place to find a substance like tin. I should go there.\nAction:"
        }
    ]
}
```
And when I print the error message, it is merely shown as 'all_probs'

**Comment by Rolnand** [comment]
Add my Wechat by id r01n4n

**Comment by Jerry-hyl** [comment]
We can see that nothing is inferred after the template `Action:` and I have used try-except pairs to confirm that the error happens during line 146-169 of fastchat_agent.py.
