### ISSUE TITLE
Questions about building state base

### ISSUE THREAD

**Issue by laaaaazyman** [zjunlp/WKM#7]
1. "In the inference stage, WKM uses the state knowledge as the key, retrieving N nearest triplets from where apre = at based on semantic similarity." May I ask which embedding model the author specifically used?
2. When building the state base, does --state_file_path need to point to the JSON file corresponding to the state knowledge generated in the second step? However, when the state=d ["conversions"] [i] ["state"] in state_base_build.py, an error message will appear saying "no state field exists". Should it be changed to state=d ["conversions"] [i] ["state_knowledge"]?

**Comment by Rolnand** [comment]
1. “During inference, we apply the embedding layer of WKM as the encoder and use the cosine similarity between sentences for retrieval.” We use the same model of WKM to embedding.
2. You are correct, we have already modified the code.
